### ISSUE TITLE
What does it mean by "one step" and "new noise"?

### ISSUE THREAD

**Issue by tgxs002** [ryanwebster90/onestep-extraction#2]
Very insightful work. But I'm not sure what does "one step" and "new noise" mean exactly? Is it that "one step" means inference for one step (directly from noise to output), and "new noise" is "one step" with another random seed?

**Comment by ryanwebster90** [comment]
hey, thanks! yeah basically one step is one denoising step (from noise to synthesis). new noise is one step with another seed as you said.

**Comment by tgxs002** [comment]
Really cool!
